//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// 
// This source code was auto-generated by Microsoft.VSDesigner, Version 4.0.30319.42000.
// 
#pragma warning disable 1591

namespace MSSeguridadFraude.AccesoDatos.MSReglasNegocio {
    using System.Diagnostics;
    using System;
    using System.Xml.Serialization;
    using System.ComponentModel;
    using System.Web.Services.Protocols;
    using System.Web.Services;
    
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.4084.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Web.Services.WebServiceBindingAttribute(Name="ServicioReglasNegocioN", Namespace="http://tempuri.org/")]
    public partial class ServicioReglasNegocioN : System.Web.Services.Protocols.SoapHttpClientProtocol {
        
        private System.Threading.SendOrPostCallback VerificarReglaOperationCompleted;
        
        private System.Threading.SendOrPostCallback VerificarReglaRestOperationCompleted;
        
        private bool useDefaultCredentialsSetExplicitly;
        
        /// <remarks/>
        public ServicioReglasNegocioN() {
            this.Url = global::MSSeguridadFraude.AccesoDatos.Properties.Settings.Default.MSSeguridadFraude_AccesoDatos_WsReglasNegocio_ServicioReglasNegocio;
            if ((this.IsLocalFileSystemWebService(this.Url) == true)) {
                this.UseDefaultCredentials = true;
                this.useDefaultCredentialsSetExplicitly = false;
            }
            else {
                this.useDefaultCredentialsSetExplicitly = true;
            }
        }
        
        public new string Url {
            get {
                return base.Url;
            }
            set {
                if ((((this.IsLocalFileSystemWebService(base.Url) == true) 
                            && (this.useDefaultCredentialsSetExplicitly == false)) 
                            && (this.IsLocalFileSystemWebService(value) == false))) {
                    base.UseDefaultCredentials = false;
                }
                base.Url = value;
            }
        }
        
        public new bool UseDefaultCredentials {
            get {
                return base.UseDefaultCredentials;
            }
            set {
                base.UseDefaultCredentials = value;
                this.useDefaultCredentialsSetExplicitly = true;
            }
        }
        
        /// <remarks/>
        public event VerificarReglaCompletedEventHandler VerificarReglaCompleted;
        
        /// <remarks/>
        public event VerificarReglaRestCompletedEventHandler VerificarReglaRestCompleted;
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/IServicioReglasNegocio/VerificarRegla", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        [return: System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public RespuestaRegla VerificarRegla([System.Xml.Serialization.XmlElementAttribute(IsNullable=true)] Verificar reglaVerificar) {
            object[] results = this.Invoke("VerificarRegla", new object[] {
                        reglaVerificar});
            return ((RespuestaRegla)(results[0]));
        }
        
        /// <remarks/>
        public void VerificarReglaAsync(Verificar reglaVerificar) {
            this.VerificarReglaAsync(reglaVerificar, null);
        }
        
        /// <remarks/>
        public void VerificarReglaAsync(Verificar reglaVerificar, object userState) {
            if ((this.VerificarReglaOperationCompleted == null)) {
                this.VerificarReglaOperationCompleted = new System.Threading.SendOrPostCallback(this.OnVerificarReglaOperationCompleted);
            }
            this.InvokeAsync("VerificarRegla", new object[] {
                        reglaVerificar}, this.VerificarReglaOperationCompleted, userState);
        }
        
        private void OnVerificarReglaOperationCompleted(object arg) {
            if ((this.VerificarReglaCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.VerificarReglaCompleted(this, new VerificarReglaCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/IServicioReglasNegocio/VerificarReglaRest", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        [return: System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public RespuestaRegla VerificarReglaRest([System.Xml.Serialization.XmlElementAttribute(IsNullable=true)] Verificar reglaVerificar) {
            object[] results = this.Invoke("VerificarReglaRest", new object[] {
                        reglaVerificar});
            return ((RespuestaRegla)(results[0]));
        }
        
        /// <remarks/>
        public void VerificarReglaRestAsync(Verificar reglaVerificar) {
            this.VerificarReglaRestAsync(reglaVerificar, null);
        }
        
        /// <remarks/>
        public void VerificarReglaRestAsync(Verificar reglaVerificar, object userState) {
            if ((this.VerificarReglaRestOperationCompleted == null)) {
                this.VerificarReglaRestOperationCompleted = new System.Threading.SendOrPostCallback(this.OnVerificarReglaRestOperationCompleted);
            }
            this.InvokeAsync("VerificarReglaRest", new object[] {
                        reglaVerificar}, this.VerificarReglaRestOperationCompleted, userState);
        }
        
        private void OnVerificarReglaRestOperationCompleted(object arg) {
            if ((this.VerificarReglaRestCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.VerificarReglaRestCompleted(this, new VerificarReglaRestCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        public new void CancelAsync(object userState) {
            base.CancelAsync(userState);
        }
        
        private bool IsLocalFileSystemWebService(string url) {
            if (((url == null) 
                        || (url == string.Empty))) {
                return false;
            }
            System.Uri wsUri = new System.Uri(url);
            if (((wsUri.Port >= 1024) 
                        && (string.Compare(wsUri.Host, "localHost", System.StringComparison.OrdinalIgnoreCase) == 0))) {
                return true;
            }
            return false;
        }
    }
    
    /// <remarks/>
    // CODEGEN: The optional WSDL extension element 'PolicyReference' from namespace 'http://schemas.xmlsoap.org/ws/2004/09/policy' was not handled.
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.4084.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Web.Services.WebServiceBindingAttribute(Name="ServicioReglasNegocio", Namespace="http://tempuri.org/")]
    public partial class ServicioReglasNegocio : System.Web.Services.Protocols.SoapHttpClientProtocol {
        
        private System.Threading.SendOrPostCallback VerificarReglaOperationCompleted;
        
        private System.Threading.SendOrPostCallback VerificarReglaRestOperationCompleted;
        
        private bool useDefaultCredentialsSetExplicitly;
        
        /// <remarks/>
        public ServicioReglasNegocio() {
            this.Url = "https://172.20.66.78:8043/ServicioReglasNegocio/ServicioReglasNegocio.svc";
            if ((this.IsLocalFileSystemWebService(this.Url) == true)) {
                this.UseDefaultCredentials = true;
                this.useDefaultCredentialsSetExplicitly = false;
            }
            else {
                this.useDefaultCredentialsSetExplicitly = true;
            }
        }
        
        public new string Url {
            get {
                return base.Url;
            }
            set {
                if ((((this.IsLocalFileSystemWebService(base.Url) == true) 
                            && (this.useDefaultCredentialsSetExplicitly == false)) 
                            && (this.IsLocalFileSystemWebService(value) == false))) {
                    base.UseDefaultCredentials = false;
                }
                base.Url = value;
            }
        }
        
        public new bool UseDefaultCredentials {
            get {
                return base.UseDefaultCredentials;
            }
            set {
                base.UseDefaultCredentials = value;
                this.useDefaultCredentialsSetExplicitly = true;
            }
        }
        
        /// <remarks/>
        public event VerificarReglaCompletedEventHandler VerificarReglaCompleted;
        
        /// <remarks/>
        public event VerificarReglaRestCompletedEventHandler VerificarReglaRestCompleted;
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/IServicioReglasNegocio/VerificarRegla", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        [return: System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public RespuestaRegla VerificarRegla([System.Xml.Serialization.XmlElementAttribute(IsNullable=true)] Verificar reglaVerificar) {
            object[] results = this.Invoke("VerificarRegla", new object[] {
                        reglaVerificar});
            return ((RespuestaRegla)(results[0]));
        }
        
        /// <remarks/>
        public void VerificarReglaAsync(Verificar reglaVerificar) {
            this.VerificarReglaAsync(reglaVerificar, null);
        }
        
        /// <remarks/>
        public void VerificarReglaAsync(Verificar reglaVerificar, object userState) {
            if ((this.VerificarReglaOperationCompleted == null)) {
                this.VerificarReglaOperationCompleted = new System.Threading.SendOrPostCallback(this.OnVerificarReglaOperationCompleted);
            }
            this.InvokeAsync("VerificarRegla", new object[] {
                        reglaVerificar}, this.VerificarReglaOperationCompleted, userState);
        }
        
        private void OnVerificarReglaOperationCompleted(object arg) {
            if ((this.VerificarReglaCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.VerificarReglaCompleted(this, new VerificarReglaCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/IServicioReglasNegocio/VerificarReglaRest", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        [return: System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public RespuestaRegla VerificarReglaRest([System.Xml.Serialization.XmlElementAttribute(IsNullable=true)] Verificar reglaVerificar) {
            object[] results = this.Invoke("VerificarReglaRest", new object[] {
                        reglaVerificar});
            return ((RespuestaRegla)(results[0]));
        }
        
        /// <remarks/>
        public void VerificarReglaRestAsync(Verificar reglaVerificar) {
            this.VerificarReglaRestAsync(reglaVerificar, null);
        }
        
        /// <remarks/>
        public void VerificarReglaRestAsync(Verificar reglaVerificar, object userState) {
            if ((this.VerificarReglaRestOperationCompleted == null)) {
                this.VerificarReglaRestOperationCompleted = new System.Threading.SendOrPostCallback(this.OnVerificarReglaRestOperationCompleted);
            }
            this.InvokeAsync("VerificarReglaRest", new object[] {
                        reglaVerificar}, this.VerificarReglaRestOperationCompleted, userState);
        }
        
        private void OnVerificarReglaRestOperationCompleted(object arg) {
            if ((this.VerificarReglaRestCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.VerificarReglaRestCompleted(this, new VerificarReglaRestCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        public new void CancelAsync(object userState) {
            base.CancelAsync(userState);
        }
        
        private bool IsLocalFileSystemWebService(string url) {
            if (((url == null) 
                        || (url == string.Empty))) {
                return false;
            }
            System.Uri wsUri = new System.Uri(url);
            if (((wsUri.Port >= 1024) 
                        && (string.Compare(wsUri.Host, "localHost", System.StringComparison.OrdinalIgnoreCase) == 0))) {
                return true;
            }
            return false;
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.4084.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://schemas.datacontract.org/2004/07/MicroServicio.Entidades.Entrada")]
    public partial class Verificar {
        
        private Auditoria auditoriaField;
        
        private System.Nullable<decimal> montoField;
        
        private bool montoFieldSpecified;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public Auditoria Auditoria {
            get {
                return this.auditoriaField;
            }
            set {
                this.auditoriaField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public System.Nullable<decimal> Monto {
            get {
                return this.montoField;
            }
            set {
                this.montoField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool MontoSpecified {
            get {
                return this.montoFieldSpecified;
            }
            set {
                this.montoFieldSpecified = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.4084.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://schemas.datacontract.org/2004/07/MicroServicio.Entidades.Auditoria")]
    public partial class Auditoria {
        
        private string accionField;
        
        private Canal canalField;
        
        private string celularField;
        
        private string codigoAgenciaField;
        
        private string codigoCentroField;
        
        private System.DateTime fechaField;
        
        private bool fechaFieldSpecified;
        
        private string hashMobilField;
        
        private string idAplicacionClienteField;
        
        private string identificacionField;
        
        private string identificadorGUIDField;
        
        private string identificadorServicioGUIDField;
        
        private string identificadorUnicoOperacionalField;
        
        private string ipClienteField;
        
        private string ipServidorProcesamientoField;
        
        private MedioInvocacion mediosInvocacionField;
        
        private string metodoField;
        
        private TransaccionFinanciera transaccionesFinancierasField;
        
        private string usuarioField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string Accion {
            get {
                return this.accionField;
            }
            set {
                this.accionField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public Canal Canal {
            get {
                return this.canalField;
            }
            set {
                this.canalField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string Celular {
            get {
                return this.celularField;
            }
            set {
                this.celularField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string CodigoAgencia {
            get {
                return this.codigoAgenciaField;
            }
            set {
                this.codigoAgenciaField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string CodigoCentro {
            get {
                return this.codigoCentroField;
            }
            set {
                this.codigoCentroField = value;
            }
        }
        
        /// <remarks/>
        public System.DateTime Fecha {
            get {
                return this.fechaField;
            }
            set {
                this.fechaField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool FechaSpecified {
            get {
                return this.fechaFieldSpecified;
            }
            set {
                this.fechaFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string HashMobil {
            get {
                return this.hashMobilField;
            }
            set {
                this.hashMobilField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string IdAplicacionCliente {
            get {
                return this.idAplicacionClienteField;
            }
            set {
                this.idAplicacionClienteField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string Identificacion {
            get {
                return this.identificacionField;
            }
            set {
                this.identificacionField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string IdentificadorGUID {
            get {
                return this.identificadorGUIDField;
            }
            set {
                this.identificadorGUIDField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string IdentificadorServicioGUID {
            get {
                return this.identificadorServicioGUIDField;
            }
            set {
                this.identificadorServicioGUIDField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string IdentificadorUnicoOperacional {
            get {
                return this.identificadorUnicoOperacionalField;
            }
            set {
                this.identificadorUnicoOperacionalField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string IpCliente {
            get {
                return this.ipClienteField;
            }
            set {
                this.ipClienteField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string IpServidorProcesamiento {
            get {
                return this.ipServidorProcesamientoField;
            }
            set {
                this.ipServidorProcesamientoField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public MedioInvocacion MediosInvocacion {
            get {
                return this.mediosInvocacionField;
            }
            set {
                this.mediosInvocacionField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string Metodo {
            get {
                return this.metodoField;
            }
            set {
                this.metodoField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public TransaccionFinanciera TransaccionesFinancieras {
            get {
                return this.transaccionesFinancierasField;
            }
            set {
                this.transaccionesFinancierasField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string Usuario {
            get {
                return this.usuarioField;
            }
            set {
                this.usuarioField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.4084.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://schemas.datacontract.org/2004/07/MicroServicio.Entidades.Multicanal")]
    public partial class Canal {
        
        private string canal1Field;
        
        private string codigoCanalField;
        
        private bool estadoField;
        
        private bool estadoFieldSpecified;
        
        private long identificadorField;
        
        private bool identificadorFieldSpecified;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("Canal", IsNullable=true)]
        public string Canal1 {
            get {
                return this.canal1Field;
            }
            set {
                this.canal1Field = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string CodigoCanal {
            get {
                return this.codigoCanalField;
            }
            set {
                this.codigoCanalField = value;
            }
        }
        
        /// <remarks/>
        public bool Estado {
            get {
                return this.estadoField;
            }
            set {
                this.estadoField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool EstadoSpecified {
            get {
                return this.estadoFieldSpecified;
            }
            set {
                this.estadoFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        public long Identificador {
            get {
                return this.identificadorField;
            }
            set {
                this.identificadorField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool IdentificadorSpecified {
            get {
                return this.identificadorFieldSpecified;
            }
            set {
                this.identificadorFieldSpecified = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.4084.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://schemas.datacontract.org/2004/07/MicroServicio.Entidades.Comun")]
    public partial class Regla {
        
        private string nombreReglaField;
        
        private bool activoField;
        
        private string codigoErrorField;
        
        private string mensajeErrorField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string NombreRegla {
            get {
                return this.nombreReglaField;
            }
            set {
                this.nombreReglaField = value;
            }
        }
        
        /// <remarks/>
        public bool Activo {
            get {
                return this.activoField;
            }
            set {
                this.activoField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string CodigoError {
            get {
                return this.codigoErrorField;
            }
            set {
                this.codigoErrorField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string MensajeError {
            get {
                return this.mensajeErrorField;
            }
            set {
                this.mensajeErrorField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.4084.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://schemas.datacontract.org/2004/07/MicroServicio.Entidades.Respuesta")]
    public partial class ERespuesta {
        
        private string nombreMetodoField;
        
        private string codigoField;
        
        private string mensajeField;
        
        private System.DateTime fechaRespuestaField;
        
        private bool errorConexionField;
        
        private bool excepcionAplicacionField;
        
        private bool operacionProcesadaField;
        
        private string numeroDocumentoOperacionField;
        
        private string identificadorUnicoTransaccionField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string NombreMetodo {
            get {
                return this.nombreMetodoField;
            }
            set {
                this.nombreMetodoField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string Codigo {
            get {
                return this.codigoField;
            }
            set {
                this.codigoField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string Mensaje {
            get {
                return this.mensajeField;
            }
            set {
                this.mensajeField = value;
            }
        }
        
        /// <remarks/>
        public System.DateTime FechaRespuesta {
            get {
                return this.fechaRespuestaField;
            }
            set {
                this.fechaRespuestaField = value;
            }
        }
        
        /// <remarks/>
        public bool ErrorConexion {
            get {
                return this.errorConexionField;
            }
            set {
                this.errorConexionField = value;
            }
        }
        
        /// <remarks/>
        public bool ExcepcionAplicacion {
            get {
                return this.excepcionAplicacionField;
            }
            set {
                this.excepcionAplicacionField = value;
            }
        }
        
        /// <remarks/>
        public bool OperacionProcesada {
            get {
                return this.operacionProcesadaField;
            }
            set {
                this.operacionProcesadaField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string NumeroDocumentoOperacion {
            get {
                return this.numeroDocumentoOperacionField;
            }
            set {
                this.numeroDocumentoOperacionField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string IdentificadorUnicoTransaccion {
            get {
                return this.identificadorUnicoTransaccionField;
            }
            set {
                this.identificadorUnicoTransaccionField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.4084.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://schemas.datacontract.org/2004/07/MicroServicio.Entidades.Salida")]
    public partial class RespuestaRegla {
        
        private ERespuesta respuestaField;
        
        private bool operacionEncriptacionField;
        
        private bool operacionPermitidaField;
        
        private Regla[] reglasValidadasField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public ERespuesta Respuesta {
            get {
                return this.respuestaField;
            }
            set {
                this.respuestaField = value;
            }
        }
        
        /// <remarks/>
        public bool OperacionEncriptacion {
            get {
                return this.operacionEncriptacionField;
            }
            set {
                this.operacionEncriptacionField = value;
            }
        }
        
        /// <remarks/>
        public bool OperacionPermitida {
            get {
                return this.operacionPermitidaField;
            }
            set {
                this.operacionPermitidaField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlArrayAttribute(IsNullable=true)]
        [System.Xml.Serialization.XmlArrayItemAttribute(Namespace="http://schemas.datacontract.org/2004/07/MicroServicio.Entidades.Comun")]
        public Regla[] ReglasValidadas {
            get {
                return this.reglasValidadasField;
            }
            set {
                this.reglasValidadasField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.4084.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://schemas.datacontract.org/2004/07/MicroServicio.Entidades.Multicanal")]
    public partial class TransaccionFinanciera {
        
        private string codigoTransaccionField;
        
        private bool estadoField;
        
        private bool estadoFieldSpecified;
        
        private long identificadorField;
        
        private bool identificadorFieldSpecified;
        
        private string transaccionField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string CodigoTransaccion {
            get {
                return this.codigoTransaccionField;
            }
            set {
                this.codigoTransaccionField = value;
            }
        }
        
        /// <remarks/>
        public bool Estado {
            get {
                return this.estadoField;
            }
            set {
                this.estadoField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool EstadoSpecified {
            get {
                return this.estadoFieldSpecified;
            }
            set {
                this.estadoFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        public long Identificador {
            get {
                return this.identificadorField;
            }
            set {
                this.identificadorField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool IdentificadorSpecified {
            get {
                return this.identificadorFieldSpecified;
            }
            set {
                this.identificadorFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string Transaccion {
            get {
                return this.transaccionField;
            }
            set {
                this.transaccionField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.4084.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://schemas.datacontract.org/2004/07/MicroServicio.Entidades.Multicanal")]
    public partial class MedioInvocacion {
        
        private string codigoMedioInvocacionField;
        
        private bool estadoField;
        
        private bool estadoFieldSpecified;
        
        private long identificadorField;
        
        private bool identificadorFieldSpecified;
        
        private string nombreMedioInvocacionField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string CodigoMedioInvocacion {
            get {
                return this.codigoMedioInvocacionField;
            }
            set {
                this.codigoMedioInvocacionField = value;
            }
        }
        
        /// <remarks/>
        public bool Estado {
            get {
                return this.estadoField;
            }
            set {
                this.estadoField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool EstadoSpecified {
            get {
                return this.estadoFieldSpecified;
            }
            set {
                this.estadoFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        public long Identificador {
            get {
                return this.identificadorField;
            }
            set {
                this.identificadorField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool IdentificadorSpecified {
            get {
                return this.identificadorFieldSpecified;
            }
            set {
                this.identificadorFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string NombreMedioInvocacion {
            get {
                return this.nombreMedioInvocacionField;
            }
            set {
                this.nombreMedioInvocacionField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.4084.0")]
    public delegate void VerificarReglaCompletedEventHandler(object sender, VerificarReglaCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.4084.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class VerificarReglaCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal VerificarReglaCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public RespuestaRegla Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((RespuestaRegla)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.4084.0")]
    public delegate void VerificarReglaRestCompletedEventHandler(object sender, VerificarReglaRestCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.4084.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class VerificarReglaRestCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal VerificarReglaRestCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public RespuestaRegla Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((RespuestaRegla)(this.results[0]));
            }
        }
    }
}

#pragma warning restore 1591