//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// 
// This source code was auto-generated by Microsoft.VSDesigner, Version 4.0.30319.42000.
// 
#pragma warning disable 1591

namespace MSSeguridadFraude.AccesoDatos.ConfiguracionCentralizada {
    using System;
    using System.Web.Services;
    using System.Diagnostics;
    using System.Web.Services.Protocols;
    using System.Xml.Serialization;
    using System.ComponentModel;
    
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.4084.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Web.Services.WebServiceBindingAttribute(Name="ConfiguracionCentralizadaSoap", Namespace="http://tcs.com/")]
    public partial class ConfiguracionCentralizada : System.Web.Services.Protocols.SoapHttpClientProtocol {
        
        private System.Threading.SendOrPostCallback ConsultarConfiguracionOperationCompleted;
        
        private bool useDefaultCredentialsSetExplicitly;
        
        /// <remarks/>
        public ConfiguracionCentralizada() {
            this.Url = global::MSSeguridadFraude.AccesoDatos.Properties.Settings.Default.MSSeguridadFraude_AccesoDatos_ConfiguracionCentralizada_ConfiguracionCentralizada;
            if ((this.IsLocalFileSystemWebService(this.Url) == true)) {
                this.UseDefaultCredentials = true;
                this.useDefaultCredentialsSetExplicitly = false;
            }
            else {
                this.useDefaultCredentialsSetExplicitly = true;
            }
        }
        
        public new string Url {
            get {
                return base.Url;
            }
            set {
                if ((((this.IsLocalFileSystemWebService(base.Url) == true) 
                            && (this.useDefaultCredentialsSetExplicitly == false)) 
                            && (this.IsLocalFileSystemWebService(value) == false))) {
                    base.UseDefaultCredentials = false;
                }
                base.Url = value;
            }
        }
        
        public new bool UseDefaultCredentials {
            get {
                return base.UseDefaultCredentials;
            }
            set {
                base.UseDefaultCredentials = value;
                this.useDefaultCredentialsSetExplicitly = true;
            }
        }
        
        /// <remarks/>
        public event ConsultarConfiguracionCompletedEventHandler ConsultarConfiguracionCompleted;
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tcs.com/ConsultarConfiguracion", RequestNamespace="http://tcs.com/", ResponseNamespace="http://tcs.com/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public Respuesta ConsultarConfiguracion(string codigoTrabajo) {
            object[] results = this.Invoke("ConsultarConfiguracion", new object[] {
                        codigoTrabajo});
            return ((Respuesta)(results[0]));
        }
        
        /// <remarks/>
        public void ConsultarConfiguracionAsync(string codigoTrabajo) {
            this.ConsultarConfiguracionAsync(codigoTrabajo, null);
        }
        
        /// <remarks/>
        public void ConsultarConfiguracionAsync(string codigoTrabajo, object userState) {
            if ((this.ConsultarConfiguracionOperationCompleted == null)) {
                this.ConsultarConfiguracionOperationCompleted = new System.Threading.SendOrPostCallback(this.OnConsultarConfiguracionOperationCompleted);
            }
            this.InvokeAsync("ConsultarConfiguracion", new object[] {
                        codigoTrabajo}, this.ConsultarConfiguracionOperationCompleted, userState);
        }
        
        private void OnConsultarConfiguracionOperationCompleted(object arg) {
            if ((this.ConsultarConfiguracionCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.ConsultarConfiguracionCompleted(this, new ConsultarConfiguracionCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        public new void CancelAsync(object userState) {
            base.CancelAsync(userState);
        }
        
        private bool IsLocalFileSystemWebService(string url) {
            if (((url == null) 
                        || (url == string.Empty))) {
                return false;
            }
            System.Uri wsUri = new System.Uri(url);
            if (((wsUri.Port >= 1024) 
                        && (string.Compare(wsUri.Host, "localHost", System.StringComparison.OrdinalIgnoreCase) == 0))) {
                return true;
            }
            return false;
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.4084.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://tcs.com/")]
    public partial class Respuesta {
        
        private int codigoField;
        
        private string mensajeInternoField;
        
        private string mensajeMostrarField;
        
        private string configuracionesField;
        
        /// <remarks/>
        public int Codigo {
            get {
                return this.codigoField;
            }
            set {
                this.codigoField = value;
            }
        }
        
        /// <remarks/>
        public string MensajeInterno {
            get {
                return this.mensajeInternoField;
            }
            set {
                this.mensajeInternoField = value;
            }
        }
        
        /// <remarks/>
        public string MensajeMostrar {
            get {
                return this.mensajeMostrarField;
            }
            set {
                this.mensajeMostrarField = value;
            }
        }
        
        /// <remarks/>
        public string Configuraciones {
            get {
                return this.configuracionesField;
            }
            set {
                this.configuracionesField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.4084.0")]
    public delegate void ConsultarConfiguracionCompletedEventHandler(object sender, ConsultarConfiguracionCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.4084.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class ConsultarConfiguracionCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal ConsultarConfiguracionCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public Respuesta Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((Respuesta)(this.results[0]));
            }
        }
    }
}

#pragma warning restore 1591