//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MSSeguridadFraude.AccesoDatos.Properties {
    
    
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Editors.SettingsDesigner.SettingsSingleFileGenerator", "17.3.0.0")]
    internal sealed partial class Settings : global::System.Configuration.ApplicationSettingsBase {
        
        private static Settings defaultInstance = ((Settings)(global::System.Configuration.ApplicationSettingsBase.Synchronized(new Settings())));
        
        public static Settings Default {
            get {
                return defaultInstance;
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.WebServiceUrl)]
        [global::System.Configuration.DefaultSettingValueAttribute("http://172.20.41.47/Tcs.ServicioConfiguracionBGR.WS/ConfiguracionCentralizada.asm" +
            "x")]
        public string MSSeguridadFraude_AccesoDatos_ConfiguracionCentralizada_ConfiguracionCentralizada {
            get {
                return ((string)(this["MSSeguridadFraude_AccesoDatos_ConfiguracionCentralizada_ConfiguracionCentralizada" +
                    ""]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.WebServiceUrl)]
        [global::System.Configuration.DefaultSettingValueAttribute("http://172.20.41.47/Tcs.ServicioConfiguracionBGR.WS/Configuracion.asmx")]
        public string MSSeguridadFraude_AccesoDatos_CodigoTrabajoWS_Configuracion {
            get {
                return ((string)(this["MSSeguridadFraude_AccesoDatos_CodigoTrabajoWS_Configuracion"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.WebServiceUrl)]
        [global::System.Configuration.DefaultSettingValueAttribute("http://rtq18617407.bgr.com/ServicioReglasNegocio/ServicioReglasNegocio.svc")]
        public string MSSeguridadFraude_AccesoDatos_WsReglasNegocio_ServicioReglasNegocio {
            get {
                return ((string)(this["MSSeguridadFraude_AccesoDatos_WsReglasNegocio_ServicioReglasNegocio"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.WebServiceUrl)]
        [global::System.Configuration.DefaultSettingValueAttribute("http://10.0.183.149/ServicioBGRInterfacesSigloMS/ListenerSigloBGRMS.asmx")]
        public string MSSeguridadFraude_AccesoDatos_WSListenerSigloBGRMS_ListenerSigloBGRMS {
            get {
                return ((string)(this["MSSeguridadFraude_AccesoDatos_WSListenerSigloBGRMS_ListenerSigloBGRMS"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.WebServiceUrl)]
        [global::System.Configuration.DefaultSettingValueAttribute("http://tcsuio068536.uio.bpichincha.com/ServicioIdentificadorUnico/ServicioIdentif" +
            "icadorUnico.svc")]
        public string MSSeguridadFraude_AccesoDatos_WSIdentificadorUnico_ServicioIdentificadorUnico {
            get {
                return ((string)(this["MSSeguridadFraude_AccesoDatos_WSIdentificadorUnico_ServicioIdentificadorUnico"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.WebServiceUrl)]
        [global::System.Configuration.DefaultSettingValueAttribute("http://bgr.cloud.vusecurity.com:80/services/FraudAnalysisWS")]
        public string MSSeguridadFraude_AccesoDatos_WsAnalisisFraude_FAWebService {
            get {
                return ((string)(this["MSSeguridadFraude_AccesoDatos_WsAnalisisFraude_FAWebService"]));
            }
        }
    }
}
