//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// 
// This source code was auto-generated by Microsoft.VSDesigner, Version 4.0.30319.42000.
// 
#pragma warning disable 1591

namespace MSSeguridadFraude.AccesoDatos.WSListenerSigloBGRMS {
    using System;
    using System.Web.Services;
    using System.Diagnostics;
    using System.Web.Services.Protocols;
    using System.Xml.Serialization;
    using System.ComponentModel;
    
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.4084.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Web.Services.WebServiceBindingAttribute(Name="ListenerSigloBGRMSSoap", Namespace="http://tempuri.org/")]
    public partial class ListenerSigloBGRMS : System.Web.Services.Protocols.SoapHttpClientProtocol {
        
        private System.Threading.SendOrPostCallback InvocarServicioGenericoOperationCompleted;
        
        private bool useDefaultCredentialsSetExplicitly;
        
        /// <remarks/>
        public ListenerSigloBGRMS() {
            this.Url = global::MSSeguridadFraude.AccesoDatos.Properties.Settings.Default.MSSeguridadFraude_AccesoDatos_WSListenerSigloBGRMS_ListenerSigloBGRMS;
            if ((this.IsLocalFileSystemWebService(this.Url) == true)) {
                this.UseDefaultCredentials = true;
                this.useDefaultCredentialsSetExplicitly = false;
            }
            else {
                this.useDefaultCredentialsSetExplicitly = true;
            }
        }
        
        public new string Url {
            get {
                return base.Url;
            }
            set {
                if ((((this.IsLocalFileSystemWebService(base.Url) == true) 
                            && (this.useDefaultCredentialsSetExplicitly == false)) 
                            && (this.IsLocalFileSystemWebService(value) == false))) {
                    base.UseDefaultCredentials = false;
                }
                base.Url = value;
            }
        }
        
        public new bool UseDefaultCredentials {
            get {
                return base.UseDefaultCredentials;
            }
            set {
                base.UseDefaultCredentials = value;
                this.useDefaultCredentialsSetExplicitly = true;
            }
        }
        
        /// <remarks/>
        public event InvocarServicioGenericoCompletedEventHandler InvocarServicioGenericoCompleted;
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/InvocarServicioGenerico", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public EDatoSalida InvocarServicioGenerico(EDatoEntrada datos) {
            object[] results = this.Invoke("InvocarServicioGenerico", new object[] {
                        datos});
            return ((EDatoSalida)(results[0]));
        }
        
        /// <remarks/>
        public void InvocarServicioGenericoAsync(EDatoEntrada datos) {
            this.InvocarServicioGenericoAsync(datos, null);
        }
        
        /// <remarks/>
        public void InvocarServicioGenericoAsync(EDatoEntrada datos, object userState) {
            if ((this.InvocarServicioGenericoOperationCompleted == null)) {
                this.InvocarServicioGenericoOperationCompleted = new System.Threading.SendOrPostCallback(this.OnInvocarServicioGenericoOperationCompleted);
            }
            this.InvokeAsync("InvocarServicioGenerico", new object[] {
                        datos}, this.InvocarServicioGenericoOperationCompleted, userState);
        }
        
        private void OnInvocarServicioGenericoOperationCompleted(object arg) {
            if ((this.InvocarServicioGenericoCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.InvocarServicioGenericoCompleted(this, new InvocarServicioGenericoCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        public new void CancelAsync(object userState) {
            base.CancelAsync(userState);
        }
        
        private bool IsLocalFileSystemWebService(string url) {
            if (((url == null) 
                        || (url == string.Empty))) {
                return false;
            }
            System.Uri wsUri = new System.Uri(url);
            if (((wsUri.Port >= 1024) 
                        && (string.Compare(wsUri.Host, "localHost", System.StringComparison.OrdinalIgnoreCase) == 0))) {
                return true;
            }
            return false;
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.4084.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://tempuri.org/")]
    public partial class EDatoEntrada {
        
        private EDatoCabecera datoCabeceraField;
        
        private string tramaXMLField;
        
        /// <remarks/>
        public EDatoCabecera datoCabecera {
            get {
                return this.datoCabeceraField;
            }
            set {
                this.datoCabeceraField = value;
            }
        }
        
        /// <remarks/>
        public string TramaXML {
            get {
                return this.tramaXMLField;
            }
            set {
                this.tramaXMLField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.4084.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://tempuri.org/")]
    public partial class EDatoCabecera {
        
        private string programaField;
        
        private string aplicacionField;
        
        private string codigoCanalBisField;
        
        private string codigoCanalSigloField;
        
        private string codigoTransaccionSigloField;
        
        private string codigoMedioInvocacionSigloField;
        
        private string numeroUnicoTransaccionField;
        
        private string tipoTransaccionSigloField;
        
        /// <remarks/>
        public string Programa {
            get {
                return this.programaField;
            }
            set {
                this.programaField = value;
            }
        }
        
        /// <remarks/>
        public string Aplicacion {
            get {
                return this.aplicacionField;
            }
            set {
                this.aplicacionField = value;
            }
        }
        
        /// <remarks/>
        public string CodigoCanalBis {
            get {
                return this.codigoCanalBisField;
            }
            set {
                this.codigoCanalBisField = value;
            }
        }
        
        /// <remarks/>
        public string CodigoCanalSiglo {
            get {
                return this.codigoCanalSigloField;
            }
            set {
                this.codigoCanalSigloField = value;
            }
        }
        
        /// <remarks/>
        public string CodigoTransaccionSiglo {
            get {
                return this.codigoTransaccionSigloField;
            }
            set {
                this.codigoTransaccionSigloField = value;
            }
        }
        
        /// <remarks/>
        public string CodigoMedioInvocacionSiglo {
            get {
                return this.codigoMedioInvocacionSigloField;
            }
            set {
                this.codigoMedioInvocacionSigloField = value;
            }
        }
        
        /// <remarks/>
        public string NumeroUnicoTransaccion {
            get {
                return this.numeroUnicoTransaccionField;
            }
            set {
                this.numeroUnicoTransaccionField = value;
            }
        }
        
        /// <remarks/>
        public string TipoTransaccionSiglo {
            get {
                return this.tipoTransaccionSigloField;
            }
            set {
                this.tipoTransaccionSigloField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.4084.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://tempuri.org/")]
    public partial class ERespuesta {
        
        private string codigoField;
        
        private string mensajeField;
        
        /// <remarks/>
        public string Codigo {
            get {
                return this.codigoField;
            }
            set {
                this.codigoField = value;
            }
        }
        
        /// <remarks/>
        public string Mensaje {
            get {
                return this.mensajeField;
            }
            set {
                this.mensajeField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.4084.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://tempuri.org/")]
    public partial class EDatoSalida {
        
        private ERespuesta respuestaField;
        
        private string datosSalidaField;
        
        /// <remarks/>
        public ERespuesta Respuesta {
            get {
                return this.respuestaField;
            }
            set {
                this.respuestaField = value;
            }
        }
        
        /// <remarks/>
        public string DatosSalida {
            get {
                return this.datosSalidaField;
            }
            set {
                this.datosSalidaField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.4084.0")]
    public delegate void InvocarServicioGenericoCompletedEventHandler(object sender, InvocarServicioGenericoCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.4084.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class InvocarServicioGenericoCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal InvocarServicioGenericoCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public EDatoSalida Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((EDatoSalida)(this.results[0]));
            }
        }
    }
}

#pragma warning restore 1591