//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// 
// This source code was auto-generated by Microsoft.VSDesigner, Version 4.0.30319.42000.
// 
#pragma warning disable 1591

namespace MSSeguridadFraude.AccesoDatos.MSIdentificadorUnico {
    using System;
    using System.Web.Services;
    using System.Diagnostics;
    using System.Web.Services.Protocols;
    using System.Xml.Serialization;
    using System.ComponentModel;
    
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.4084.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Web.Services.WebServiceBindingAttribute(Name="ServicioIdentificadorUnicoN", Namespace="http://tempuri.org/")]
    public partial class ServicioIdentificadorUnicoN : System.Web.Services.Protocols.SoapHttpClientProtocol {
        
        private System.Threading.SendOrPostCallback GenerarIdentificadorUnicoOperationCompleted;
        
        private System.Threading.SendOrPostCallback GenerarIdentificadorUnicoRestOperationCompleted;
        
        private bool useDefaultCredentialsSetExplicitly;
        
        /// <remarks/>
        public ServicioIdentificadorUnicoN() {
            this.Url = global::MSSeguridadFraude.AccesoDatos.Properties.Settings.Default.MSSeguridadFraude_AccesoDatos_WSIdentificadorUnico_ServicioIdentificadorUnico;
            if ((this.IsLocalFileSystemWebService(this.Url) == true)) {
                this.UseDefaultCredentials = true;
                this.useDefaultCredentialsSetExplicitly = false;
            }
            else {
                this.useDefaultCredentialsSetExplicitly = true;
            }
        }
        
        public new string Url {
            get {
                return base.Url;
            }
            set {
                if ((((this.IsLocalFileSystemWebService(base.Url) == true) 
                            && (this.useDefaultCredentialsSetExplicitly == false)) 
                            && (this.IsLocalFileSystemWebService(value) == false))) {
                    base.UseDefaultCredentials = false;
                }
                base.Url = value;
            }
        }
        
        public new bool UseDefaultCredentials {
            get {
                return base.UseDefaultCredentials;
            }
            set {
                base.UseDefaultCredentials = value;
                this.useDefaultCredentialsSetExplicitly = true;
            }
        }
        
        /// <remarks/>
        public event GenerarIdentificadorUnicoCompletedEventHandler GenerarIdentificadorUnicoCompleted;
        
        /// <remarks/>
        public event GenerarIdentificadorUnicoRestCompletedEventHandler GenerarIdentificadorUnicoRestCompleted;
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/IServicioIdentificadorUnico/GenerarIdentificadorUnico", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        [return: System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public RespuestaIdentificador GenerarIdentificadorUnico([System.Xml.Serialization.XmlElementAttribute(IsNullable=true)] Consulta operacionGenerarId) {
            object[] results = this.Invoke("GenerarIdentificadorUnico", new object[] {
                        operacionGenerarId});
            return ((RespuestaIdentificador)(results[0]));
        }
        
        /// <remarks/>
        public void GenerarIdentificadorUnicoAsync(Consulta operacionGenerarId) {
            this.GenerarIdentificadorUnicoAsync(operacionGenerarId, null);
        }
        
        /// <remarks/>
        public void GenerarIdentificadorUnicoAsync(Consulta operacionGenerarId, object userState) {
            if ((this.GenerarIdentificadorUnicoOperationCompleted == null)) {
                this.GenerarIdentificadorUnicoOperationCompleted = new System.Threading.SendOrPostCallback(this.OnGenerarIdentificadorUnicoOperationCompleted);
            }
            this.InvokeAsync("GenerarIdentificadorUnico", new object[] {
                        operacionGenerarId}, this.GenerarIdentificadorUnicoOperationCompleted, userState);
        }
        
        private void OnGenerarIdentificadorUnicoOperationCompleted(object arg) {
            if ((this.GenerarIdentificadorUnicoCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.GenerarIdentificadorUnicoCompleted(this, new GenerarIdentificadorUnicoCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/IServicioIdentificadorUnico/GenerarIdentificadorUnicoRest", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        [return: System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public RespuestaIdentificador GenerarIdentificadorUnicoRest([System.Xml.Serialization.XmlElementAttribute(IsNullable=true)] Consulta operacionGenerarId) {
            object[] results = this.Invoke("GenerarIdentificadorUnicoRest", new object[] {
                        operacionGenerarId});
            return ((RespuestaIdentificador)(results[0]));
        }
        
        /// <remarks/>
        public void GenerarIdentificadorUnicoRestAsync(Consulta operacionGenerarId) {
            this.GenerarIdentificadorUnicoRestAsync(operacionGenerarId, null);
        }
        
        /// <remarks/>
        public void GenerarIdentificadorUnicoRestAsync(Consulta operacionGenerarId, object userState) {
            if ((this.GenerarIdentificadorUnicoRestOperationCompleted == null)) {
                this.GenerarIdentificadorUnicoRestOperationCompleted = new System.Threading.SendOrPostCallback(this.OnGenerarIdentificadorUnicoRestOperationCompleted);
            }
            this.InvokeAsync("GenerarIdentificadorUnicoRest", new object[] {
                        operacionGenerarId}, this.GenerarIdentificadorUnicoRestOperationCompleted, userState);
        }
        
        private void OnGenerarIdentificadorUnicoRestOperationCompleted(object arg) {
            if ((this.GenerarIdentificadorUnicoRestCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.GenerarIdentificadorUnicoRestCompleted(this, new GenerarIdentificadorUnicoRestCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        public new void CancelAsync(object userState) {
            base.CancelAsync(userState);
        }
        
        private bool IsLocalFileSystemWebService(string url) {
            if (((url == null) 
                        || (url == string.Empty))) {
                return false;
            }
            System.Uri wsUri = new System.Uri(url);
            if (((wsUri.Port >= 1024) 
                        && (string.Compare(wsUri.Host, "localHost", System.StringComparison.OrdinalIgnoreCase) == 0))) {
                return true;
            }
            return false;
        }
    }
    
    /// <remarks/>
    // CODEGEN: The optional WSDL extension element 'PolicyReference' from namespace 'http://schemas.xmlsoap.org/ws/2004/09/policy' was not handled.
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.4084.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Web.Services.WebServiceBindingAttribute(Name="ServicioIdentificadorUnico", Namespace="http://tempuri.org/")]
    public partial class ServicioIdentificadorUnico : System.Web.Services.Protocols.SoapHttpClientProtocol {
        
        private System.Threading.SendOrPostCallback GenerarIdentificadorUnicoOperationCompleted;
        
        private System.Threading.SendOrPostCallback GenerarIdentificadorUnicoRestOperationCompleted;
        
        private bool useDefaultCredentialsSetExplicitly;
        
        /// <remarks/>
        public ServicioIdentificadorUnico() {
            this.Url = "https://10.0.183.151:8084/ServicioIdentificadorUnico/ServicioIdentificadorUnico.s" +
                "vc";
            if ((this.IsLocalFileSystemWebService(this.Url) == true)) {
                this.UseDefaultCredentials = true;
                this.useDefaultCredentialsSetExplicitly = false;
            }
            else {
                this.useDefaultCredentialsSetExplicitly = true;
            }
        }
        
        public new string Url {
            get {
                return base.Url;
            }
            set {
                if ((((this.IsLocalFileSystemWebService(base.Url) == true) 
                            && (this.useDefaultCredentialsSetExplicitly == false)) 
                            && (this.IsLocalFileSystemWebService(value) == false))) {
                    base.UseDefaultCredentials = false;
                }
                base.Url = value;
            }
        }
        
        public new bool UseDefaultCredentials {
            get {
                return base.UseDefaultCredentials;
            }
            set {
                base.UseDefaultCredentials = value;
                this.useDefaultCredentialsSetExplicitly = true;
            }
        }
        
        /// <remarks/>
        public event GenerarIdentificadorUnicoCompletedEventHandler GenerarIdentificadorUnicoCompleted;
        
        /// <remarks/>
        public event GenerarIdentificadorUnicoRestCompletedEventHandler GenerarIdentificadorUnicoRestCompleted;
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/IServicioIdentificadorUnico/GenerarIdentificadorUnico", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        [return: System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public RespuestaIdentificador GenerarIdentificadorUnico([System.Xml.Serialization.XmlElementAttribute(IsNullable=true)] Consulta operacionGenerarId) {
            object[] results = this.Invoke("GenerarIdentificadorUnico", new object[] {
                        operacionGenerarId});
            return ((RespuestaIdentificador)(results[0]));
        }
        
        /// <remarks/>
        public void GenerarIdentificadorUnicoAsync(Consulta operacionGenerarId) {
            this.GenerarIdentificadorUnicoAsync(operacionGenerarId, null);
        }
        
        /// <remarks/>
        public void GenerarIdentificadorUnicoAsync(Consulta operacionGenerarId, object userState) {
            if ((this.GenerarIdentificadorUnicoOperationCompleted == null)) {
                this.GenerarIdentificadorUnicoOperationCompleted = new System.Threading.SendOrPostCallback(this.OnGenerarIdentificadorUnicoOperationCompleted);
            }
            this.InvokeAsync("GenerarIdentificadorUnico", new object[] {
                        operacionGenerarId}, this.GenerarIdentificadorUnicoOperationCompleted, userState);
        }
        
        private void OnGenerarIdentificadorUnicoOperationCompleted(object arg) {
            if ((this.GenerarIdentificadorUnicoCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.GenerarIdentificadorUnicoCompleted(this, new GenerarIdentificadorUnicoCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/IServicioIdentificadorUnico/GenerarIdentificadorUnicoRest", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        [return: System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public RespuestaIdentificador GenerarIdentificadorUnicoRest([System.Xml.Serialization.XmlElementAttribute(IsNullable=true)] Consulta operacionGenerarId) {
            object[] results = this.Invoke("GenerarIdentificadorUnicoRest", new object[] {
                        operacionGenerarId});
            return ((RespuestaIdentificador)(results[0]));
        }
        
        /// <remarks/>
        public void GenerarIdentificadorUnicoRestAsync(Consulta operacionGenerarId) {
            this.GenerarIdentificadorUnicoRestAsync(operacionGenerarId, null);
        }
        
        /// <remarks/>
        public void GenerarIdentificadorUnicoRestAsync(Consulta operacionGenerarId, object userState) {
            if ((this.GenerarIdentificadorUnicoRestOperationCompleted == null)) {
                this.GenerarIdentificadorUnicoRestOperationCompleted = new System.Threading.SendOrPostCallback(this.OnGenerarIdentificadorUnicoRestOperationCompleted);
            }
            this.InvokeAsync("GenerarIdentificadorUnicoRest", new object[] {
                        operacionGenerarId}, this.GenerarIdentificadorUnicoRestOperationCompleted, userState);
        }
        
        private void OnGenerarIdentificadorUnicoRestOperationCompleted(object arg) {
            if ((this.GenerarIdentificadorUnicoRestCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.GenerarIdentificadorUnicoRestCompleted(this, new GenerarIdentificadorUnicoRestCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        public new void CancelAsync(object userState) {
            base.CancelAsync(userState);
        }
        
        private bool IsLocalFileSystemWebService(string url) {
            if (((url == null) 
                        || (url == string.Empty))) {
                return false;
            }
            System.Uri wsUri = new System.Uri(url);
            if (((wsUri.Port >= 1024) 
                        && (string.Compare(wsUri.Host, "localHost", System.StringComparison.OrdinalIgnoreCase) == 0))) {
                return true;
            }
            return false;
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.4084.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://schemas.datacontract.org/2004/07/MSSeguridadFraude.Entidades.Entrada")]
    public partial class Consulta {
        
        private Entorno entornoField;
        
        private Auditoria auditoriaField;
        
        private string tipoTransaccionField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public Entorno Entorno {
            get {
                return this.entornoField;
            }
            set {
                this.entornoField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public Auditoria Auditoria {
            get {
                return this.auditoriaField;
            }
            set {
                this.auditoriaField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string TipoTransaccion {
            get {
                return this.tipoTransaccionField;
            }
            set {
                this.tipoTransaccionField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.4084.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://schemas.datacontract.org/2004/07/MSSeguridadFraude.Entidades.Comun")]
    public partial class Entorno {
        
        private string autorizadorField;
        
        private short centroField;
        
        private bool centroFieldSpecified;
        
        private short dominioField;
        
        private bool dominioFieldSpecified;
        
        private short empresaField;
        
        private bool empresaFieldSpecified;
        
        private string entorno1Field;
        
        private string idiomaField;
        
        private short longInField;
        
        private bool longInFieldSpecified;
        
        private short longOutField;
        
        private bool longOutFieldSpecified;
        
        private short nodoField;
        
        private bool nodoFieldSpecified;
        
        private string programaField;
        
        private string usuarioField;
        
        private string versionField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string Autorizador {
            get {
                return this.autorizadorField;
            }
            set {
                this.autorizadorField = value;
            }
        }
        
        /// <remarks/>
        public short Centro {
            get {
                return this.centroField;
            }
            set {
                this.centroField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool CentroSpecified {
            get {
                return this.centroFieldSpecified;
            }
            set {
                this.centroFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        public short Dominio {
            get {
                return this.dominioField;
            }
            set {
                this.dominioField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool DominioSpecified {
            get {
                return this.dominioFieldSpecified;
            }
            set {
                this.dominioFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        public short Empresa {
            get {
                return this.empresaField;
            }
            set {
                this.empresaField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool EmpresaSpecified {
            get {
                return this.empresaFieldSpecified;
            }
            set {
                this.empresaFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("Entorno", IsNullable=true)]
        public string Entorno1 {
            get {
                return this.entorno1Field;
            }
            set {
                this.entorno1Field = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string Idioma {
            get {
                return this.idiomaField;
            }
            set {
                this.idiomaField = value;
            }
        }
        
        /// <remarks/>
        public short LongIn {
            get {
                return this.longInField;
            }
            set {
                this.longInField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool LongInSpecified {
            get {
                return this.longInFieldSpecified;
            }
            set {
                this.longInFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        public short LongOut {
            get {
                return this.longOutField;
            }
            set {
                this.longOutField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool LongOutSpecified {
            get {
                return this.longOutFieldSpecified;
            }
            set {
                this.longOutFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        public short Nodo {
            get {
                return this.nodoField;
            }
            set {
                this.nodoField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool NodoSpecified {
            get {
                return this.nodoFieldSpecified;
            }
            set {
                this.nodoFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string Programa {
            get {
                return this.programaField;
            }
            set {
                this.programaField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string Usuario {
            get {
                return this.usuarioField;
            }
            set {
                this.usuarioField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string Version {
            get {
                return this.versionField;
            }
            set {
                this.versionField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.4084.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://schemas.datacontract.org/2004/07/MSSeguridadFraude.Entidades.Respuesta")]
    public partial class ERespuesta {
        
        private string codigoField;
        
        private string mensajeField;
        
        private System.DateTime fechaRespuestaField;
        
        private bool errorConexionField;
        
        private bool excepcionAplicacionField;
        
        private bool operacionProcesadaField;
        
        private string numeroDocumentoOperacionField;
        
        private string identificadorUnicoTransaccionField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string Codigo {
            get {
                return this.codigoField;
            }
            set {
                this.codigoField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string Mensaje {
            get {
                return this.mensajeField;
            }
            set {
                this.mensajeField = value;
            }
        }
        
        /// <remarks/>
        public System.DateTime FechaRespuesta {
            get {
                return this.fechaRespuestaField;
            }
            set {
                this.fechaRespuestaField = value;
            }
        }
        
        /// <remarks/>
        public bool ErrorConexion {
            get {
                return this.errorConexionField;
            }
            set {
                this.errorConexionField = value;
            }
        }
        
        /// <remarks/>
        public bool ExcepcionAplicacion {
            get {
                return this.excepcionAplicacionField;
            }
            set {
                this.excepcionAplicacionField = value;
            }
        }
        
        /// <remarks/>
        public bool OperacionProcesada {
            get {
                return this.operacionProcesadaField;
            }
            set {
                this.operacionProcesadaField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string NumeroDocumentoOperacion {
            get {
                return this.numeroDocumentoOperacionField;
            }
            set {
                this.numeroDocumentoOperacionField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string IdentificadorUnicoTransaccion {
            get {
                return this.identificadorUnicoTransaccionField;
            }
            set {
                this.identificadorUnicoTransaccionField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.4084.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://schemas.datacontract.org/2004/07/MSSeguridadFraude.Entidades.Salida")]
    public partial class RespuestaIdentificador {
        
        private string codigoIdentificadorField;
        
        private ERespuesta respuestaField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string CodigoIdentificador {
            get {
                return this.codigoIdentificadorField;
            }
            set {
                this.codigoIdentificadorField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public ERespuesta Respuesta {
            get {
                return this.respuestaField;
            }
            set {
                this.respuestaField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.4084.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://schemas.datacontract.org/2004/07/MSSeguridadFraude.Entidades.Multicanal")]
    public partial class TransaccionFinanciera {
        
        private string codigoTransaccionField;
        
        private bool estadoField;
        
        private bool estadoFieldSpecified;
        
        private long identificadorField;
        
        private bool identificadorFieldSpecified;
        
        private string transaccionField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string CodigoTransaccion {
            get {
                return this.codigoTransaccionField;
            }
            set {
                this.codigoTransaccionField = value;
            }
        }
        
        /// <remarks/>
        public bool Estado {
            get {
                return this.estadoField;
            }
            set {
                this.estadoField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool EstadoSpecified {
            get {
                return this.estadoFieldSpecified;
            }
            set {
                this.estadoFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        public long Identificador {
            get {
                return this.identificadorField;
            }
            set {
                this.identificadorField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool IdentificadorSpecified {
            get {
                return this.identificadorFieldSpecified;
            }
            set {
                this.identificadorFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string Transaccion {
            get {
                return this.transaccionField;
            }
            set {
                this.transaccionField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.4084.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://schemas.datacontract.org/2004/07/MSSeguridadFraude.Entidades.Multicanal")]
    public partial class MedioInvocacion {
        
        private string codigoMedioInvocacionField;
        
        private bool estadoField;
        
        private bool estadoFieldSpecified;
        
        private long identificadorField;
        
        private bool identificadorFieldSpecified;
        
        private string nombreMedioInvocacionField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string CodigoMedioInvocacion {
            get {
                return this.codigoMedioInvocacionField;
            }
            set {
                this.codigoMedioInvocacionField = value;
            }
        }
        
        /// <remarks/>
        public bool Estado {
            get {
                return this.estadoField;
            }
            set {
                this.estadoField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool EstadoSpecified {
            get {
                return this.estadoFieldSpecified;
            }
            set {
                this.estadoFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        public long Identificador {
            get {
                return this.identificadorField;
            }
            set {
                this.identificadorField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool IdentificadorSpecified {
            get {
                return this.identificadorFieldSpecified;
            }
            set {
                this.identificadorFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string NombreMedioInvocacion {
            get {
                return this.nombreMedioInvocacionField;
            }
            set {
                this.nombreMedioInvocacionField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.4084.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://schemas.datacontract.org/2004/07/MSSeguridadFraude.Entidades.Multicanal")]
    public partial class Canal {
        
        private string canal1Field;
        
        private string codigoCanalField;
        
        private bool estadoField;
        
        private bool estadoFieldSpecified;
        
        private long identificadorField;
        
        private bool identificadorFieldSpecified;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("Canal", IsNullable=true)]
        public string Canal1 {
            get {
                return this.canal1Field;
            }
            set {
                this.canal1Field = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string CodigoCanal {
            get {
                return this.codigoCanalField;
            }
            set {
                this.codigoCanalField = value;
            }
        }
        
        /// <remarks/>
        public bool Estado {
            get {
                return this.estadoField;
            }
            set {
                this.estadoField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool EstadoSpecified {
            get {
                return this.estadoFieldSpecified;
            }
            set {
                this.estadoFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        public long Identificador {
            get {
                return this.identificadorField;
            }
            set {
                this.identificadorField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool IdentificadorSpecified {
            get {
                return this.identificadorFieldSpecified;
            }
            set {
                this.identificadorFieldSpecified = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.4084.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://schemas.datacontract.org/2004/07/MSSeguridadFraude.Entidades.Auditoria")]
    public partial class Auditoria {
        
        private string accionField;
        
        private Canal canalField;
        
        private string celularField;
        
        private string codigoAgenciaField;
        
        private string codigoCentroField;
        
        private System.DateTime fechaField;
        
        private bool fechaFieldSpecified;
        
        private string hashMobilField;
        
        private string idAplicacionClienteField;
        
        private string identificacionField;
        
        private string identificadorGUIDField;
        
        private string identificadorServicioGUIDField;
        
        private string identificadorUnicoOperacionalField;
        
        private string ipClienteField;
        
        private string ipServidorProcesamientoField;
        
        private MedioInvocacion mediosInvocacionField;
        
        private string metodoField;
        
        private TransaccionFinanciera transaccionesFinancierasField;
        
        private string usuarioField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string Accion {
            get {
                return this.accionField;
            }
            set {
                this.accionField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public Canal Canal {
            get {
                return this.canalField;
            }
            set {
                this.canalField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string Celular {
            get {
                return this.celularField;
            }
            set {
                this.celularField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string CodigoAgencia {
            get {
                return this.codigoAgenciaField;
            }
            set {
                this.codigoAgenciaField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string CodigoCentro {
            get {
                return this.codigoCentroField;
            }
            set {
                this.codigoCentroField = value;
            }
        }
        
        /// <remarks/>
        public System.DateTime Fecha {
            get {
                return this.fechaField;
            }
            set {
                this.fechaField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool FechaSpecified {
            get {
                return this.fechaFieldSpecified;
            }
            set {
                this.fechaFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string HashMobil {
            get {
                return this.hashMobilField;
            }
            set {
                this.hashMobilField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string IdAplicacionCliente {
            get {
                return this.idAplicacionClienteField;
            }
            set {
                this.idAplicacionClienteField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string Identificacion {
            get {
                return this.identificacionField;
            }
            set {
                this.identificacionField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string IdentificadorGUID {
            get {
                return this.identificadorGUIDField;
            }
            set {
                this.identificadorGUIDField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string IdentificadorServicioGUID {
            get {
                return this.identificadorServicioGUIDField;
            }
            set {
                this.identificadorServicioGUIDField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string IdentificadorUnicoOperacional {
            get {
                return this.identificadorUnicoOperacionalField;
            }
            set {
                this.identificadorUnicoOperacionalField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string IpCliente {
            get {
                return this.ipClienteField;
            }
            set {
                this.ipClienteField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string IpServidorProcesamiento {
            get {
                return this.ipServidorProcesamientoField;
            }
            set {
                this.ipServidorProcesamientoField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public MedioInvocacion MediosInvocacion {
            get {
                return this.mediosInvocacionField;
            }
            set {
                this.mediosInvocacionField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string Metodo {
            get {
                return this.metodoField;
            }
            set {
                this.metodoField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public TransaccionFinanciera TransaccionesFinancieras {
            get {
                return this.transaccionesFinancierasField;
            }
            set {
                this.transaccionesFinancierasField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string Usuario {
            get {
                return this.usuarioField;
            }
            set {
                this.usuarioField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.4084.0")]
    public delegate void GenerarIdentificadorUnicoCompletedEventHandler(object sender, GenerarIdentificadorUnicoCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.4084.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class GenerarIdentificadorUnicoCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal GenerarIdentificadorUnicoCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public RespuestaIdentificador Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((RespuestaIdentificador)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.4084.0")]
    public delegate void GenerarIdentificadorUnicoRestCompletedEventHandler(object sender, GenerarIdentificadorUnicoRestCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.4084.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class GenerarIdentificadorUnicoRestCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal GenerarIdentificadorUnicoRestCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public RespuestaIdentificador Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((RespuestaIdentificador)(this.results[0]));
            }
        }
    }
}

#pragma warning restore 1591